# Generated by Django 3.1.1 on 2021-03-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincaraousalad',
            old_name='mainText',
            new_name='FirstLine',
        ),
        migrations.RenameField(
            model_name='maincaraousalad',
            old_name='subText',
            new_name='SecondLine',
        ),
        migrations.AddField(
            model_name='maincaraousalad',
            name='ThirdLine',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
