# Generated by Django 3.1.1 on 2021-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210329_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
