# Generated by Django 3.1.1 on 2021-03-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210330_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
