# Generated by Django 3.1.1 on 2021-03-30 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20210330_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.AddField(
            model_name='addresses',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='houseNo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='pin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
