# Generated by Django 3.1.1 on 2021-03-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210330_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='addr',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
