# Generated by Django 3.1.1 on 2021-03-30 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_addresses_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='addr',
        ),
    ]
