# Generated by Django 3.1.1 on 2021-03-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_cartitembyuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartitemByUser',
        ),
    ]
